In [3]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [4]:
_lableEncoder = {}

data = pd.read_csv('merge_extended.txt',sep=";")
transformed_data = data.drop(['Category', 'MethodName'], axis=1)
transformed_label =data.loc[:,['Category']]
for column in transformed_data.columns:
    _lableEncoder[column] = LabelEncoder()


for encoder in _lableEncoder.keys():
    transformed_data[encoder] = _lableEncoder[encoder].fit_transform(transformed_data[encoder])



In [5]:
binaryData = transformed_data.copy()
binaryLabel = transformed_label.copy()

In [6]:
binaryLabel.loc[ transformed_label['Category'] != "Normal", "Category"] = "Sensitive"
binaryLabel.loc[transformed_label['Category'] == "Normal", "Category"] = "Normal"


In [7]:
binaryLabel

Category
0    NonEvasion
1    NonEvasion
2    NonEvasion
3    NonEvasion
4    NonEvasion
..          ...
294     Evasion
295     Evasion
296     Evasion
297     Evasion
298     Evasion

[299 rows x 1 columns]

In [8]:
## binary calssifier
X = binaryData.iloc[:].values
Y = binaryLabel.iloc[:].values

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33,  random_state=88)

clf = RandomForestClassifier(max_depth=10, random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [9]:
y_pred

array(['NonEvasion', 'NonEvasion', 'NonEvasion', 'NonEvasion',
       'NonEvasion', 'Evasion', 'Evasion', 'NonEvasion', 'Evasion',
       'Evasion', 'Evasion', 'NonEvasion', 'Evasion', 'NonEvasion',
       'NonEvasion', 'Evasion', 'Evasion', 'Evasion', 'Evasion',
       'Evasion', 'NonEvasion', 'Evasion', 'Evasion', 'Evasion',
       'NonEvasion', 'Evasion', 'Evasion', 'Evasion', 'NonEvasion',
       'NonEvasion', 'NonEvasion', 'Evasion', 'Evasion', 'NonEvasion',
       'NonEvasion', 'NonEvasion', 'Evasion', 'Evasion', 'Evasion',
       'NonEvasion', 'NonEvasion', 'NonEvasion', 'Evasion', 'NonEvasion',
       'NonEvasion', 'NonEvasion', 'NonEvasion', 'Evasion', 'NonEvasion',
       'NonEvasion', 'NonEvasion', 'NonEvasion', 'NonEvasion', 'Evasion',
       'Evasion', 'Evasion', 'Evasion', 'NonEvasion', 'Evasion',
       'NonEvasion', 'Evasion', 'Evasion', 'Evasion', 'Evasion',
       'Evasion', 'NonEvasion', 'Evasion', 'NonEvasion', 'NonEvasion',
       'NonEvasion', 'NonEvasion', 'NonEv

In [10]:
print('#####confusion_matrix####')
print(confusion_matrix(y_test,y_pred))
print('#####classification_report####')
print(classification_report(y_test,y_pred))
print('#####accuracy_score####')
print(accuracy_score(y_test, y_pred))

#####confusion_matrix####
[[43  6]
 [ 7 43]]
#####classification_report####
              precision    recall  f1-score   support

     Evasion       0.86      0.88      0.87        49
  NonEvasion       0.88      0.86      0.87        50

    accuracy                           0.87        99
   macro avg       0.87      0.87      0.87        99
weighted avg       0.87      0.87      0.87        99

#####accuracy_score####
0.8686868686868687


In [11]:
secondData = transformed_data.copy()
secondLabel = transformed_label.copy()

drop_index = secondData[ secondLabel['Category'] =='Normal'].index
secondData.drop(drop_index, inplace = True)
secondLabel.drop(drop_index, inplace = True)



In [12]:
X = secondData.iloc[:].values
Y = secondLabel.iloc[:].values

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33,  random_state=88)

clf = RandomForestClassifier(max_depth=12, random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys


In [13]:
print('#####confusion_matrix####')
print(confusion_matrix(y_test,y_pred))
print('#####classification_report####')
print(classification_report(y_test,y_pred))
print('#####accuracy_score####')
print(accuracy_score(y_test, y_pred))

#####confusion_matrix####
[[ 4  0  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  5  1  1  5]
 [ 1  0  0  2  0  0]
 [ 1  0  0  0  5  0]
 [ 0  0  1  0  0 23]]
#####classification_report####
                precision    recall  f1-score   support

    FileAccess       0.67      1.00      0.80         4
IntegrityCheck       1.00      1.00      1.00         1
      Location       0.83      0.42      0.56        12
           SMS       0.67      0.67      0.67         3
          Time       0.83      0.83      0.83         6
 antiEmulation       0.82      0.96      0.88        24

      accuracy                           0.80        50
     macro avg       0.80      0.81      0.79        50
  weighted avg       0.81      0.80      0.78        50

#####accuracy_score####
0.8
